from fortress.exceptions import FortressException


class SlithIRError(FortressException):
    pass
