class FortressException(Exception):
    pass


class FortressError(FortressException):
    pass
